### ISSUE TITLE
error？

### ISSUE THREAD

**Issue by rongdongliu** [TinkerPatch/tinkerpatch-easy-sample#4]
com.tinkerpatch.easy_sample E/Tinker.PatchRequestCallback: onPatchSyncFail stack:  java.io.FileNotFoundException: http://q.tinkerpatch.com/c7531eca96a3f07a/1.0?d=ab1a89b3-2a5b-46fe-928a-c470e417bb96&v=1483603002816
                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
                                                               at com.tinkerpatch.sdk.server.c.a$a.run(SourceFile:131)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by simpleton** [comment]
@rongdongliu 麻烦确认下，是否在tinkerpatch.com的配置了相应的appVersion，已经appKey是否正确。是否选择了` 开发预览`.

开发预览是需要在手机上安装一个工具来打开开关的，[debug tools](http://tinkerpatch.com/Index/sdk)

**Comment by rongdongliu** [comment]
wo 在仔细看文档






------------------ 原始邮件 ------------------
发件人: "Sim Sun";<notifications@github.com>;
发送时间: 2017年1月5日(星期四) 下午4:40
收件人: "TinkerPatch/tinkerpatch-easy-sample"<tinkerpatch-easy-sample@noreply.github.com>; 
抄送: "刘栋荣"<1124466590@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [TinkerPatch/tinkerpatch-easy-sample] error？ (#4)




@rongdongliu 麻烦确认下，是否在tinkerpatch.com的配置了相应的appVersion，已经appKey是否正确。是否选择了开发预览.
 
开发预览是需要在手机上安装一个工具来打开开关的，debug tools
