### ISSUE TITLE
有个这样的错误，不知道怎么出来的

### ISSUE THREAD

**Issue by bacy** [TinkerPatch/tinkerpatch-easy-sample#8]
01-13 14:06:04.068 29875-29875/? E/Tinker.SampleUncaughtExHandler: uncaughtException:Field 'com.tencent.tinker.lib.service.TinkerPatchService.notificationId' is inaccessible to class 'com.tencent.tinker.lib.service.TinkerPatchService' (declaration of 'com.tencent.tinker.lib.service.TinkerPatchService' appears in /data/user/0/com.example.administrator.tinkertest/tinker/patch-941df674/dex/classes.dex.jar)
01-13 14:06:04.068 29875-29875/? W/Tinker.VersionInfo: increaseCrashTimes fail, current PatchMd5: 8a06391d6e1a01a66cef6d15ede016a0, try increase md5: 941df674f26caf9c23b2c562c6790ed2
01-13 14:06:04.069 29875-29875/? E/Tinker.SampleUncaughtExHandler: tinker has fast crash 1 times
01-13 14:06:04.069 29875-29875/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.IllegalAccessError: Field 'com.tencent.tinker.lib.service.TinkerPatchService.notificationId' is inaccessible to class 'com.tencent.tinker.lib.service.TinkerPatchService' (declaration of 'com.tencent.tinker.lib.service.TinkerPatchService' appears in /data/user/0/com.example.administrator.tinkertest/tinker/patch-941df674/dex/classes.dex.jar)
                                                               at com.tencent.tinker.lib.service.TinkerPatchService.<clinit>(SourceFile:47)
                                                               at java.lang.Class.newInstance(Native Method)
                                                               at android.app.ActivityThread.handleCreateService(ActivityThread.java:3310)
                                                               at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:156)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by simpleton** [comment]
@bacy 麻烦提供下出现问题的手机型号、ROM版本号、已经使用的tinkerpatch的版本，多谢。

**Comment by simpleton** [comment]
可以尝试下1.1.0的版本，看还是否有这个问题。1.0.1的版本如果开启application反射的功能的话，在android N上一个兼容性问题。

**Comment by bacy** [comment]
@simpleton 今天刚上班。问题手机确实是android N。用1.0.1后，错误日志没有再输出。非常感谢！！！

**Comment by simpleton** [comment]
最近版是1.1.1~ 遇到新的问题随时联系
