### ISSUE TITLE
tinkerEnable = false 问题

### ISSUE THREAD

**Issue by small-tree** [TinkerPatch/tinkerpatch-easy-sample#9]
怎么判断tinkerEnable 的值

01-14 14:58:10.021 17736-17736/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.tinkerpatch.easy_sample, PID: 17736
                                                   java.lang.RuntimeException: Unable to create application com.tinkerpatch.easy_sample.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:applicationLike must not be null.
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4416)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:145)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:applicationLike must not be null.
                                                       at com.tinkerpatch.sdk.TinkerPatch$Builder.<init>(SourceFile:402)
                                                       at com.tinkerpatch.sdk.TinkerPatch.init(SourceFile:117)
                                                       at com.tinkerpatch.easy_sample.SampleApplication.onCreate(SampleApplication.java:64)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4413)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:145) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by simpleton** [comment]
@small-tree 多谢提醒，这块忘记给出示例了。可以参照我link的这个commit改造下，后续我看大家需求，要不要做一个no-op的lib，让大家来debugCompile。
